version: '3'
services:
  sdc_4:
    build: .
    image: loyzious/sdc_4_streamlit_fastapi:v.0.1.0
    # https://hub.docker.com/r/loyzious/sdc_4/
    ports:
      - '8000:8000'
      - '8501:8501'
    command: streamlit run dashboard.py
