# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ds21m001-sdc4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2493c0c6cf114fa39ce5d9b41641b3a0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_00aafb55e9034b8687808bdcd9087a76 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2493c0c6cf114fa39ce5d9b41641b3a0 }}/loyzious/sdc_4_streamlit_fastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ds21m001-sdc4'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7837d21076314445b9d00012477cc010 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2493c0c6cf114fa39ce5d9b41641b3a0 }}/loyzious/sdc_4_streamlit_fastapi:${{ github.sha }}'