# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ds21m001-sdc4 Docker2Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3cc343dcc53c42ffabd5157ef7093fef }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7cb1e4a1dbd24f9081d4cc6467adf6f5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3cc343dcc53c42ffabd5157ef7093fef }}/sdc_4_streamlit_fastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ds21m001-sdc4'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_db1318e822d5459396221ce53b2b5849 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3cc343dcc53c42ffabd5157ef7093fef }}/sdc_4_streamlit_fastapi:${{ github.sha }}'
